[package]
name = "the-wilds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.195"
serde_derive = "1.0.195"
shared = { path = "../shared" }
